### ISSUE TITLE
Talk

### ISSUE THREAD

**Issue by E13ctron** [Suman-Jaiswal/Project-LINKS#1]
@Suman-Jaiswal , you are learning react ??

**Comment by Suman-Jaiswal** [comment]
@Amar-2003 Yes bro. Bhaiya recommended me to learn. It will help me in gymkhana website handling.

**Comment by E13ctron** [comment]
Cool, I am going to learn Flutter and Angular @Suman-Jaiswal

**Comment by Suman-Jaiswal** [comment]
I don't know about that but giving you a "noice", all the best. @Amar-2003

**Comment by E13ctron** [comment]
Thanks and same to you bro @Suman-Jaiswal
